---
apiVersion: batch/v1
kind: Job
metadata:
  name: big-quantum-web-job
  namespace: twb-stg-twbapps-01
spec:
  #  parallelism: 2
  completions: 1
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: big-quantum-web-job
          image: 675287654630.dkr.ecr.ap-southeast-1.amazonaws.com/big-quantum-web:tags
          env:
            - name: ENVIRONMENT
              value: "staging"
            - name: NODE_ENV
              value: "development"
      restartPolicy: Never
