---
apiVersion: batch/v1
kind: Job
metadata:
  name: big-quantum-web-job
  namespace: twb-prod-twbapps-02
spec:
  completions: 1
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: big-quantum-web-job
          image: 675287654630.dkr.ecr.ap-southeast-1.amazonaws.com/big-quantum-web:tags
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: NODE_ENV
              value: "production"
      restartPolicy: Never
